#################################################
# Config: Development                           #
#################################################
# (production settings go in _config.build.yml) #

#############
# Meta info #
#############

name: Save the Lock
url: https://savethelock.org
description: Strong locks save lives.
timezone: America/New_York
googleanalytics: UA-26576645-30

pathlead: '' # use this if you need a leading slash or directory on asset paths

author:
  googleid: 102356128596404327231
  twitterid: 382376904
  twitter: fightfortheftr

###########
# Content #
###########

future: true
show_drafts: true
permalink: /:title/ # See Jekyll documentation for permalink styles

defaults:
  - scope:
      path: ''
    values:
      layout: default

#############
# Compiling #
#############

exclude: ['img']
keep_files: ['img', 'js', 'css']

markdown: kramdown
