#################################################
# Config: Development                           #
#################################################
# (production settings go in _config.build.yml) #

#############
# Meta info #
#############

url: https://savesecurity.org
petitions_api: http://0.0.0.0:9104
timezone: America/New_York
googleanalytics: UA-26576645-30

################
# Social Media #
################

name: Save Security
description: Strong security saves lives.
sharetitle: Don’t let the FBI backdoor Apple.
sharedescription: This is way bigger than the iPhone…
twittertext: Strong locks save lives. Don’t let the FBI backdoor Apple—this is way bigger than the iPhone.

author:
  googleid: 102356128596404327231
  twitterid: 382376904
  twitter: fightfortheftr

###########
# Content #
###########

future: true
show_drafts: true
permalink: /:title/

defaults:
  - scope:
      path: ''
    values:
      layout: default

#############
# Compiling #
#############

exclude: ['img']
keep_files: ['img', 'js', 'css']

markdown: kramdown
